import { beforeEach, describe, expect, it } from 'vitest';
import { useStoryboardStore } from '@/stores/storyboard-store';
import { useAudioStore } from '@/stores/audio-store';
import { useTimelineStore } from '@/stores/timeline-store';
import { useProviderStore } from '@/stores/provider-store';
import type { Scene, Storyboard } from '@/types/scene';

function makeScene(id: string, order: number): Scene {
  return {
    id,
    order,
    screenshotId: `shot-${id}`,
    title: `Scene ${id}`,
    description: '',
    duration: 4,
    transition: { type: 'fade', duration: 0.5, easing: 'smooth' },
    camera: { type: 'static' },
    overlays: [],
  };
}

function makeStoryboard(scenes: Scene[]): Storyboard {
  return {
    id: 'sb-1',
    projectId: 'p-1',
    scenes,
    version: 1,
    status: 'draft',
    createdAt: '2026-08-17T10:00:00.000Z',
    updatedAt: '2026-08-17T10:00:00.000Z',
  };
}

describe('storyboard-store', () => {
  beforeEach(() => {
    useStoryboardStore.setState({ storyboard: null });
  });

  it('reorders scenes and rewrites order indices', () => {
    useStoryboardStore
      .getState()
      .setStoryboard(makeStoryboard([makeScene('a', 0), makeScene('b', 1)]));
    useStoryboardStore.getState().reorderScenes(['b', 'a']);
    const scenes = useStoryboardStore.getState().storyboard?.scenes ?? [];
    expect(scenes.map((s) => s.id)).toEqual(['b', 'a']);
    expect(scenes[0].order).toBe(0);
    expect(scenes[1].order).toBe(1);
  });

  it('updates a single scene', () => {
    useStoryboardStore.getState().setStoryboard(makeStoryboard([makeScene('a', 0)]));
    useStoryboardStore.getState().updateScene('a', { duration: 8 });
    expect(useStoryboardStore.getState().storyboard?.scenes[0].duration).toBe(8);
  });

  it('removes a scene and renumbers the rest', () => {
    useStoryboardStore
      .getState()
      .setStoryboard(makeStoryboard([makeScene('a', 0), makeScene('b', 1), makeScene('c', 2)]));
    useStoryboardStore.getState().removeScene('b');
    const scenes = useStoryboardStore.getState().storyboard?.scenes ?? [];
    expect(scenes.map((s) => s.id)).toEqual(['a', 'c']);
    expect(scenes[1].order).toBe(1);
  });
});

describe('audio-store', () => {
  beforeEach(() => {
    useAudioStore.setState({ track: null, keyframes: [], suggestions: [] });
  });

  it('accepts an auto-sync suggestion into keyframes', () => {
    useAudioStore.setState({
      track: {
        id: 't-1',
        projectId: 'p-1',
        fileUrl: '/uploads/a.mp3',
        duration: 10,
        transcript: { text: '', language: 'en', segments: [] },
        createdAt: '2026-08-17T10:00:00.000Z',
      },
    });
    useAudioStore
      .getState()
      .setSuggestions([{ sceneId: 'sc-1', startTime: 1, endTime: 4, confidence: 0.9 }]);
    useAudioStore
      .getState()
      .acceptSuggestion({ sceneId: 'sc-1', startTime: 1, endTime: 4, confidence: 0.9 });
    const state = useAudioStore.getState();
    expect(state.keyframes).toHaveLength(1);
    expect(state.keyframes[0].projectId).toBe('p-1');
    expect(state.keyframes[0].isAutoGenerated).toBe(true);
    expect(state.suggestions).toHaveLength(0);
  });

  it('upserts keyframes by id', () => {
    useAudioStore.setState({
      keyframes: [
        {
          id: 'k-1',
          projectId: 'p',
          sceneId: 's',
          startTime: 0,
          endTime: 2,
          transitionDuration: 0.5,
          isAutoGenerated: false,
        },
      ],
    });
    useAudioStore.getState().upsertKeyframe({
      id: 'k-1',
      projectId: 'p',
      sceneId: 's',
      startTime: 0,
      endTime: 5,
      transitionDuration: 0.5,
      isAutoGenerated: false,
    });
    expect(useAudioStore.getState().keyframes).toHaveLength(1);
    expect(useAudioStore.getState().keyframes[0].endTime).toBe(5);
  });
});

describe('timeline-store', () => {
  beforeEach(() => {
    useTimelineStore.setState({
      clips: [],
      duration: 0,
      playhead: 0,
      isPlaying: false,
      playbackSpeed: 1,
      zoom: 1,
    });
  });

  it('upserts clips and keeps them unique by id', () => {
    useTimelineStore.getState().upsertClip({ id: 'c-1', track: 'video', start: 0, end: 4 });
    useTimelineStore.getState().upsertClip({ id: 'c-2', track: 'voiceover', start: 0, end: 4 });
    useTimelineStore.getState().upsertClip({ id: 'c-1', track: 'video', start: 2, end: 6 });
    const clips = useTimelineStore.getState().clips;
    expect(clips).toHaveLength(2);
    expect(clips.find((c) => c.id === 'c-1')?.end).toBe(6);
  });
});

describe('provider-store', () => {
  beforeEach(() => useProviderStore.getState().reset());

  it('stores provider connection status', () => {
    useProviderStore.getState().setProviderStatus({
      providerId: 'openai',
      status: 'connected',
      keyHint: 'a3Bx',
      lastValidatedAt: '2026-08-17T10:00:00.000Z',
    });
    expect(useProviderStore.getState().providers.openai.status).toBe('connected');
  });

  it('stores task routing config', () => {
    useProviderStore
      .getState()
      .setRouting('storyboard', { taskType: 'storyboard', primaryProviderId: 'gemini' });
    expect(useProviderStore.getState().routing.storyboard.primaryProviderId).toBe('gemini');
  });
});
