import { describe, expect, it } from 'vitest';
import { render, screen } from '@testing-library/react';
import { KeyframeMarkers } from '@/components/audio/keyframe-markers';
import type { Keyframe } from '@/types/keyframe';

const KEYFRAMES: Keyframe[] = [
  {
    id: 'k-1',
    projectId: 'p',
    sceneId: 'sc-1',
    startTime: 0,
    endTime: 5,
    transitionDuration: 0.5,
    isAutoGenerated: false,
  },
  {
    id: 'k-2',
    projectId: 'p',
    sceneId: 'sc-2',
    startTime: 10,
    endTime: 15,
    transitionDuration: 0.5,
    isAutoGenerated: true,
  },
];

describe('KeyframeMarkers', () => {
  it('positions markers by time over a 20s duration', () => {
    render(<KeyframeMarkers keyframes={KEYFRAMES} duration={20} />);
    const bars = document.querySelectorAll('[aria-hidden="true"] > div');
    const first = bars[0] as HTMLElement;
    const second = bars[1] as HTMLElement;
    // k-1: 0/20 = 0%, width 5/20 = 25%; k-2: 10/20 = 50%, width 5/20 = 25%.
    expect(first.style.left).toBe('0%');
    expect(first.style.width).toBe('25%');
    expect(second.style.left).toBe('50%');
    expect(second.style.width).toBe('25%');
  });

  it('renders time labels', () => {
    render(<KeyframeMarkers keyframes={KEYFRAMES} duration={20} />);
    expect(screen.getByText('00:00.0')).toBeInTheDocument();
    expect(screen.getByText('00:10.0')).toBeInTheDocument();
  });

  it('returns null for zero duration', () => {
    const { container } = render(<KeyframeMarkers keyframes={KEYFRAMES} duration={0} />);
    expect(container.innerHTML).toBe('');
  });

  it('exposes remove buttons when onRemove is provided', () => {
    render(<KeyframeMarkers keyframes={KEYFRAMES} duration={20} onRemove={() => undefined} />);
    expect(screen.getAllByLabelText(/Remove keyframe/)).toHaveLength(2);
  });
});
