import { describe, expect, it, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { TimingTable } from '@/components/audio/timing-table';
import type { Keyframe } from '@/types/keyframe';
import type { Scene } from '@/types/scene';

function makeScene(id: string, title: string, duration: number): Scene {
  return {
    id,
    order: 0,
    screenshotId: `shot-${id}`,
    title,
    description: '',
    duration,
    transition: { type: 'fade', duration: 0.6, easing: 'smooth' },
    camera: { type: 'static' },
    overlays: [],
  };
}

const SCENES = [makeScene('sc-1', 'Hero', 4), makeScene('sc-2', 'Pricing', 5)];

const KEYFRAMES: Keyframe[] = [
  {
    id: 'k-1',
    projectId: 'p',
    sceneId: 'sc-1',
    startTime: 2,
    endTime: 6,
    transitionDuration: 0.5,
    isAutoGenerated: false,
  },
];

describe('TimingTable', () => {
  it('renders scene rows with timing derived from keyframes', () => {
    render(<TimingTable scenes={SCENES} keyframes={KEYFRAMES} />);
    expect(screen.getByText('Hero')).toBeInTheDocument();
    expect(screen.getByText('Pricing')).toBeInTheDocument();
    // Hero has a keyframe (2–6s), Pricing has none (— in Start and End).
    expect(screen.getByText('00:02.0')).toBeInTheDocument();
    expect(screen.getAllByText('—')).toHaveLength(2);
  });

  it('shows keyframe-based duration in the duration input', () => {
    render(<TimingTable scenes={SCENES} keyframes={KEYFRAMES} />);
    const heroDuration = screen.getByLabelText('Duration for Hero') as HTMLInputElement;
    expect(heroDuration.value).toBe('4.0'); // 6 - 2
  });

  it('emits duration changes', () => {
    const onChange = vi.fn();
    render(<TimingTable scenes={SCENES} keyframes={KEYFRAMES} onDurationChange={onChange} />);
    fireEvent.change(screen.getByLabelText('Duration for Hero'), { target: { value: '8' } });
    expect(onChange).toHaveBeenCalledWith('sc-1', 8);
  });

  it('falls back to scene duration when no keyframe exists', () => {
    render(<TimingTable scenes={[makeScene('sc-9', 'Outro', 7)]} keyframes={[]} />);
    expect((screen.getByLabelText('Duration for Outro') as HTMLInputElement).value).toBe('7.0');
  });
});
