'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ArrowLeft, ArrowRight, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ProjectLayout } from '@/components/shared/project-layout';
import { ProviderGate } from '@/components/shared/provider-gate';
import { useProviderStore } from '@/stores/provider-store';
import { trpc } from '@/lib/trpc/client';
import {
  AudioUploader,
  AutoSyncButton,
  SceneSyncView,
  TimingTable,
  TranscriptPanel,
} from '@/components/audio';
import type { Keyframe } from '@/types/keyframe';

export default function ProjectAudioPage() {
  const params = useParams<{ id: string }>();
  const projectId = params.id;

  const providers = useProviderStore((s) => s.providers);
  const hasProvider = Object.values(providers).some((p) => p.status === 'connected');

  const projectQuery = trpc.project.get.useQuery({ id: projectId });
  const storyboardQuery = trpc.storyboard.get.useQuery({ projectId });
  const audioQuery = trpc.audio.get.useQuery({ projectId });
  const saveKeyframesMutation = trpc.audio.saveKeyframes.useMutation();

  const [isUploading, setIsUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [currentTime, setCurrentTime] = useState(0);
  const [keyframes, setKeyframes] = useState<Keyframe[]>([]);

  useEffect(() => {
    if (audioQuery.data) {
      setKeyframes(audioQuery.data.keyframes);
    }
  }, [audioQuery.data]);

  const screenshotUrls = useMemo(() => {
    const map: Record<string, string> = {};
    for (const capture of projectQuery.data?.captures ?? []) {
      map[capture.id] = capture.screenshotUrl;
    }
    return map;
  }, [projectQuery.data?.captures]);

  const track = audioQuery.data?.track ?? null;
  const scenes = storyboardQuery.data?.scenes ?? [];

  const handleUpload = async (file: File) => {
    setIsUploading(true);
    setUploadError(null);
    try {
      const form = new FormData();
      form.append('projectId', projectId);
      form.append('file', file);
      const res = await fetch('/api/audio', { method: 'POST', body: form });
      const body = (await res.json()) as {
        error: boolean;
        data?: { track: unknown };
        message?: string;
      };
      if (!res.ok || body.error) {
        throw new Error(body.error ? (body.message ?? 'Upload failed') : 'Upload failed');
      }
      await audioQuery.refetch();
    } catch (error) {
      setUploadError(error instanceof Error ? error.message : 'Upload failed');
    } finally {
      setIsUploading(false);
    }
  };

  const handleKeyframesChange = (next: Keyframe[]) => {
    setKeyframes(next);
    const withProject = next.map((kf) => ({
      sceneId: kf.sceneId,
      startTime: kf.startTime,
      endTime: kf.endTime,
      transitionDuration: kf.transitionDuration,
      isAutoGenerated: kf.isAutoGenerated,
    }));
    void saveKeyframesMutation
      .mutateAsync({ projectId, keyframes: withProject })
      .catch(() => undefined);
  };

  return (
    <ProjectLayout projectName={projectQuery.data?.name ?? 'Loading project…'} currentPhase={2}>
      <div className="space-y-6">
        <div className="flex items-start justify-between gap-4">
          <div>
            <Link
              href={`/projects/${projectId}/storyboard`}
              className="mb-1 flex items-center gap-1.5 text-sm text-zinc-500 transition-colors hover:text-zinc-900"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to storyboard
            </Link>
            <h1 className="text-2xl font-semibold tracking-tight text-zinc-900">Voiceover</h1>
            <p className="mt-0.5 text-sm text-zinc-500">
              Upload narration, sync scenes to the transcript, and lock the timing.
            </p>
          </div>
          {track && scenes.length > 0 && (
            <Button
              render={<Link href={`/projects/${projectId}/generate`} />}
              className="bg-violet-600 hover:bg-violet-500"
            >
              Continue to generate <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          )}
        </div>

        {audioQuery.isLoading && (
          <div className="flex h-40 items-center justify-center text-sm text-zinc-400">
            <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Loading…
          </div>
        )}

        {!audioQuery.isLoading && !track && (
          <div className="mx-auto max-w-xl space-y-4">
            {!hasProvider && <ProviderGate />}
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Upload your voiceover</CardTitle>
              </CardHeader>
              <CardContent>
                <AudioUploader onUpload={handleUpload} isUploading={isUploading} />
                {uploadError && <p className="mt-3 text-sm text-red-600">{uploadError}</p>}
              </CardContent>
            </Card>
          </div>
        )}

        {!audioQuery.isLoading && track && (
          <>
            <SceneSyncView
              audioUrl={track.fileUrl}
              keyframes={keyframes}
              scenes={scenes}
              screenshotUrls={screenshotUrls}
              currentTime={currentTime}
              onKeyframesChange={handleKeyframesChange}
              onPlayheadChange={setCurrentTime}
            />

            <div className="grid gap-4 lg:grid-cols-2">
              <Card>
                <CardHeader className="pb-3">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-base">Transcript</CardTitle>
                    <AutoSyncButton
                      projectId={projectId}
                      disabled={scenes.length === 0}
                      onComplete={() => void audioQuery.refetch()}
                    />
                  </div>
                </CardHeader>
                <CardContent>
                  <TranscriptPanel
                    transcript={track.transcript}
                    currentTime={currentTime}
                    onSeek={(time) => setCurrentTime(time)}
                  />
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Scene timing</CardTitle>
                </CardHeader>
                <CardContent>
                  <TimingTable
                    scenes={scenes}
                    keyframes={keyframes}
                    onDurationChange={(sceneId, duration) => {
                      setKeyframes((prev) =>
                        prev.map((kf) =>
                          kf.sceneId === sceneId
                            ? { ...kf, endTime: kf.startTime + Math.max(duration, 1) }
                            : kf,
                        ),
                      );
                    }}
                  />
                </CardContent>
              </Card>
            </div>
          </>
        )}
      </div>
    </ProjectLayout>
  );
}
