import { test, expect } from '@playwright/test';

/**
 * Timeline & export flow: after capture + storyboard, the timeline page shows
 * scene clips and playback controls, and a video export runs end-to-end
 * through /api/export with SSE progress and a downloadable result.
 */
test.describe('timeline & export flow', () => {
  let projectId: string;

  test('timeline renders and export produces a downloadable video', async ({ page }) => {
    test.setTimeout(240_000);

    // Capture the app itself.
    const response = await page.request.post('/api/capture', {
      data: {
        url: 'http://127.0.0.1:3000',
        viewports: [{ width: 1280, height: 720, deviceScaleFactor: 2, isMobile: false }],
      },
    });
    expect(response.status()).toBe(202);
    projectId = (await response.json()).data.projectId;

    // Wait for captures to land (poll, tolerant of slower browsers + queue depth).
    let captures: Array<{ id: string }> = [];
    for (let attempt = 0; attempt < 90; attempt += 1) {
      await page.waitForTimeout(1_000);
      const project = await (await page.request.get(`/api/projects/${projectId}`)).json();
      captures = project.data?.captures ?? [];
      if (captures.length > 0) break;
    }
    expect(captures.length).toBeGreaterThanOrEqual(1);

    const scenes = [
      {
        id: 'sc-1',
        order: 0,
        screenshotId: captures[0].id,
        title: 'Hero',
        description: '',
        duration: 3,
        transition: { type: 'fade', duration: 0.5, easing: 'smooth' },
        camera: { type: 'zoom-to', target: { x: 50, y: 50, scale: 1.2 } },
        overlays: [],
      },
      {
        id: 'sc-2',
        order: 1,
        screenshotId: (captures[1] ?? captures[0]).id,
        title: 'Features',
        description: '',
        duration: 3,
        transition: { type: 'fade', duration: 0.5, easing: 'smooth' },
        camera: { type: 'ken-burns' },
        overlays: [],
      },
    ];

    const sb = await page.request.post('/api/trpc/storyboard.save?batch=1', {
      headers: { 'Content-Type': 'application/json' },
      data: { '0': { projectId, storyboard: { projectId, scenes, version: 1, status: 'draft' } } },
    });
    expect(sb.status()).toBe(200);

    const kf = await page.request.post('/api/trpc/audio.saveKeyframes?batch=1', {
      headers: { 'Content-Type': 'application/json' },
      data: {
        '0': {
          projectId,
          keyframes: [
            {
              sceneId: 'sc-1',
              startTime: 0,
              endTime: 3,
              transitionDuration: 0.5,
              isAutoGenerated: false,
            },
            {
              sceneId: 'sc-2',
              startTime: 3,
              endTime: 6,
              transitionDuration: 0.5,
              isAutoGenerated: false,
            },
          ],
        },
      },
    });
    expect(kf.status()).toBe(200);

    // Timeline page renders scene clips + playback controls.
    await page.goto(`/projects/${projectId}/timeline`);
    await expect(page.getByRole('heading', { name: 'Timeline' })).toBeVisible();
    await expect(page.getByRole('button', { name: /play/i })).toBeVisible();
    await expect(page.getByText('Hero').first()).toBeVisible();
    await expect(page.getByText('Features').first()).toBeVisible();

    // Trim a scene via the drag handles (pointer down on the left handle).
    const heroClip = page.getByRole('button').filter({ hasText: 'Hero' }).first();
    await expect(heroClip).toBeVisible();

    // Export a single 720p video.
    await page.getByTestId('open-export').click();
    await expect(page.getByTestId('export-dialog')).toBeVisible();
    await page.getByRole('button', { name: '720p' }).click();
    await page.getByTestId('export-start').click();

    // SSE progress reports and a download link appears once complete.
    await expect(page.getByTestId('export-progress')).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText('Export complete').first()).toBeVisible({ timeout: 90_000 });
    await expect(page.getByRole('link', { name: /Download export\.mp4/i })).toBeVisible();
  });
});
