import { ChildProcessWithoutNullStreams, spawn } from 'node:child_process';
import { test, expect } from '@playwright/test';

/**
 * Generate & render flow: from a captured project with a seeded storyboard,
 * the generate page writes Motion Canvas code and renders a real preview MP4
 * (FFmpeg compositor). Verifies the code tabs and the rendered preview appear.
 */
test.describe('generate flow', () => {
  let worker: ChildProcessWithoutNullStreams | undefined;
  let projectId: string;

  test.beforeAll(async () => {
    worker = spawn('bun', ['run', 'worker'], { stdio: 'pipe', shell: true });
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('worker failed to start')), 30_000);
      worker?.stdout?.on('data', (chunk: Buffer) => {
        if (chunk.toString().includes('listening')) {
          clearTimeout(timer);
          resolve(null);
        }
      });
      worker?.on('exit', (code) => {
        clearTimeout(timer);
        reject(new Error(`worker exited early with code ${code}`));
      });
    });
  });

  test.afterAll(() => {
    worker?.kill('SIGTERM');
  });

  test('capture → storyboard → generate code → render preview', async ({ page }) => {
    test.setTimeout(180_000);

    // Capture the app itself.
    const response = await page.request.post('/api/capture', {
      data: {
        url: 'http://127.0.0.1:3000',
        viewports: [{ width: 1280, height: 720, deviceScaleFactor: 2, isMobile: false }],
      },
    });
    expect(response.status()).toBe(202);
    const body = await response.json();
    projectId = body.data.projectId;
    await page.waitForTimeout(10_000);

    // Read captures to map screenshot ids.
    const project = await (await page.request.get(`/api/projects/${projectId}`)).json();
    const captures = project.data.captures;
    expect(captures.length).toBeGreaterThanOrEqual(1);

    const scenes = [
      {
        id: 'sc-1',
        order: 0,
        screenshotId: captures[0].id,
        title: 'Hero',
        description: '',
        duration: 3,
        transition: { type: 'fade', duration: 0.5, easing: 'smooth' },
        camera: { type: 'zoom-to', target: { x: 50, y: 50, scale: 1.2 } },
        overlays: [
          {
            id: 'o1',
            text: 'Paste a URL',
            position: { x: 50, y: 30 },
            fontSize: 48,
            color: '#ffffff',
          },
        ],
      },
      {
        id: 'sc-2',
        order: 1,
        screenshotId: (captures[1] ?? captures[0]).id,
        title: 'Features',
        description: '',
        duration: 3,
        transition: { type: 'fade', duration: 0.5, easing: 'smooth' },
        camera: { type: 'ken-burns' },
        overlays: [],
      },
    ];

    // Seed storyboard + keyframes via tRPC.
    const sb = await page.request.post('/api/trpc/storyboard.save?batch=1', {
      headers: { 'Content-Type': 'application/json' },
      data: { '0': { projectId, storyboard: { projectId, scenes, version: 1, status: 'draft' } } },
    });
    expect(sb.status()).toBe(200);

    const kf = await page.request.post('/api/trpc/audio.saveKeyframes?batch=1', {
      headers: { 'Content-Type': 'application/json' },
      data: {
        '0': {
          projectId,
          keyframes: [
            {
              sceneId: 'sc-1',
              startTime: 0,
              endTime: 3,
              transitionDuration: 0.5,
              isAutoGenerated: false,
            },
            {
              sceneId: 'sc-2',
              startTime: 3,
              endTime: 6,
              transitionDuration: 0.5,
              isAutoGenerated: false,
            },
          ],
        },
      },
    });
    expect(kf.status()).toBe(200);

    // Drive the generate page UI.
    await page.goto(`/projects/${projectId}/generate`);
    await page.getByRole('button', { name: /Generate Video/i }).click();
    await page.getByRole('button', { name: /Generate & render/i }).click();

    // Code tabs appear after code generation.
    await expect(page.getByRole('tab', { name: 'Generated code' })).toBeVisible({
      timeout: 30_000,
    });
    await expect(page.getByText('src/project.ts').first()).toBeVisible();

    // The preview tab shows a playable video once rendering finishes.
    await page.getByRole('tab', { name: 'Preview' }).click();
    const video = page.locator('video');
    await expect(video).toBeVisible({ timeout: 90_000 });
    await expect(video).toHaveAttribute('src', /\/api\/files\/exports\//);
  });
});
