export interface Keyframe {
  id: string;
  projectId: string;
  sceneId: string;
  startTime: number;
  endTime: number;
  transitionDuration: number;
  isAutoGenerated: boolean;
}

export interface AudioTrack {
  id: string;
  projectId: string;
  fileUrl: string;
  duration: number;
  transcript: {
    text: string;
    language: string;
    segments: Array<{
      id: number;
      text: string;
      start: number;
      end: number;
      words: Array<{ word: string; start: number; end: number }>;
    }>;
  };
  createdAt: string;
}

export interface AutoSyncSuggestion {
  sceneId: string;
  startTime: number;
  endTime: number;
  confidence: number;
}
