import { create } from 'zustand';
import type { AudioTrack, AutoSyncSuggestion, Keyframe } from '@/types/keyframe';

interface AudioState {
  track: AudioTrack | null;
  keyframes: Keyframe[];
  suggestions: AutoSyncSuggestion[];
  setTrack: (track: AudioTrack | null) => void;
  setKeyframes: (keyframes: Keyframe[]) => void;
  upsertKeyframe: (keyframe: Keyframe) => void;
  removeKeyframe: (id: string) => void;
  setSuggestions: (suggestions: AutoSyncSuggestion[]) => void;
  acceptSuggestion: (suggestion: AutoSyncSuggestion) => void;
}

export const useAudioStore = create<AudioState>((set) => ({
  track: null,
  keyframes: [],
  suggestions: [],
  setTrack: (track) => set({ track }),
  setKeyframes: (keyframes) => set({ keyframes }),
  upsertKeyframe: (keyframe) =>
    set((state) => {
      const exists = state.keyframes.some((kf) => kf.id === keyframe.id);
      return {
        keyframes: exists
          ? state.keyframes.map((kf) => (kf.id === keyframe.id ? keyframe : kf))
          : [...state.keyframes, keyframe],
      };
    }),
  removeKeyframe: (id) =>
    set((state) => ({ keyframes: state.keyframes.filter((kf) => kf.id !== id) })),
  setSuggestions: (suggestions) => set({ suggestions }),
  acceptSuggestion: (suggestion) =>
    set((state) => {
      const keyframe: Keyframe = {
        id: `kf-${suggestion.sceneId}`,
        projectId: state.track?.projectId ?? '',
        sceneId: suggestion.sceneId,
        startTime: suggestion.startTime,
        endTime: suggestion.endTime,
        transitionDuration: 0.5,
        isAutoGenerated: true,
      };
      const keyframes = [
        ...state.keyframes.filter((kf) => kf.sceneId !== suggestion.sceneId),
        keyframe,
      ];
      return {
        keyframes,
        suggestions: state.suggestions.filter((s) => s.sceneId !== suggestion.sceneId),
      };
    }),
}));
