import { eq } from 'drizzle-orm';
import { db } from '@/lib/db';
import { audioTracks, keyframes, storyboards } from '@/lib/db/schema';
import { buildAutoSyncSuggestions } from './auto-sync';
import type { AutoSyncSuggestion, AudioTrack, Keyframe } from '@/types/keyframe';
import type { Scene } from '@/types/scene';

export interface AudioState {
  track: AudioTrack | null;
  keyframes: Keyframe[];
}

function toAudioTrack(row: typeof audioTracks.$inferSelect): AudioTrack {
  return {
    id: row.id,
    projectId: row.projectId,
    fileUrl: row.fileUrl,
    duration: row.duration,
    transcript: row.transcript as AudioTrack['transcript'],
    createdAt: row.createdAt.toISOString(),
  };
}

function toKeyframe(row: typeof keyframes.$inferSelect): Keyframe {
  return {
    id: row.id,
    projectId: row.projectId,
    sceneId: row.sceneId,
    startTime: row.startTime,
    endTime: row.endTime,
    transitionDuration: row.transitionDuration,
    isAutoGenerated: row.isAutoGenerated,
  };
}

export async function getAudioState(projectId: string): Promise<AudioState> {
  const [trackRows, keyframeRows] = await Promise.all([
    db.select().from(audioTracks).where(eq(audioTracks.projectId, projectId)).limit(1),
    db.select().from(keyframes).where(eq(keyframes.projectId, projectId)),
  ]);
  return {
    track: trackRows[0] ? toAudioTrack(trackRows[0]) : null,
    keyframes: keyframeRows.map(toKeyframe),
  };
}

export async function persistTrack(
  projectId: string,
  track: { fileUrl: string; duration: number; transcript: AudioTrack['transcript'] },
): Promise<AudioTrack> {
  await db.delete(audioTracks).where(eq(audioTracks.projectId, projectId));
  const inserted = await db
    .insert(audioTracks)
    .values({
      projectId,
      fileUrl: track.fileUrl,
      duration: track.duration,
      transcript: track.transcript as unknown as object,
    })
    .returning();
  return toAudioTrack(inserted[0]);
}

export async function replaceKeyframes(
  projectId: string,
  keyframeInputs: Array<{
    sceneId: string;
    startTime: number;
    endTime: number;
    transitionDuration: number;
    isAutoGenerated: boolean;
  }>,
): Promise<Keyframe[]> {
  await db.delete(keyframes).where(eq(keyframes.projectId, projectId));
  if (keyframeInputs.length === 0) return [];
  const inserted = await db
    .insert(keyframes)
    .values(keyframeInputs.map((input) => ({ projectId, ...input })))
    .returning();
  return inserted.map(toKeyframe);
}

/**
 * Computes keyframe suggestions from the stored audio track + storyboard and
 * persists them as auto-generated keyframes. Returns the suggestions.
 */
export async function autoSyncKeyframes(projectId: string): Promise<AutoSyncSuggestion[]> {
  const { track } = await getAudioState(projectId);
  if (!track) return [];

  const storyboardRows = await db
    .select()
    .from(storyboards)
    .where(eq(storyboards.projectId, projectId))
    .limit(1);
  const storyboard = storyboardRows[0];
  if (!storyboard) return [];

  const scenes = storyboard.scenes as unknown as Scene[];
  const suggestions = buildAutoSyncSuggestions({
    transcript: track.transcript,
    scenes,
  });

  await replaceKeyframes(
    projectId,
    suggestions.map((suggestion) => ({
      sceneId: suggestion.sceneId,
      startTime: suggestion.startTime,
      endTime: suggestion.endTime,
      transitionDuration: 0.5,
      isAutoGenerated: true,
    })),
  );

  return suggestions;
}
