'use client';

import { useEffect, useRef, useState } from 'react';
import WaveSurfer from 'wavesurfer.js';
import RegionsPlugin, { type Region } from 'wavesurfer.js/dist/plugins/regions';
import { Button } from '@/components/ui/button';
import { Pause, Play } from 'lucide-react';
import { formatTime } from '@/lib/audio/transcription';
import { KeyframeMarkers } from './keyframe-markers';
import type { Keyframe } from '@/types/keyframe';

function buildRegions(keyframes: Keyframe[]) {
  return keyframes.map((keyframe) => ({
    id: keyframe.id,
    start: keyframe.startTime,
    end: keyframe.endTime,
    color: '#10b981',
    drag: true,
    resize: true,
  }));
}

export function WaveformView({
  audioUrl,
  keyframes,
  onKeyframesChange,
  onPlayheadChange,
  canAdd = true,
}: {
  audioUrl: string;
  keyframes: Keyframe[];
  onKeyframesChange: (keyframes: Keyframe[]) => void;
  onPlayheadChange?: (time: number) => void;
  canAdd?: boolean;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const wavesurferRef = useRef<WaveSurfer | null>(null);
  const regionsRef = useRef<RegionsPlugin | null>(null);
  const keyframesRef = useRef(keyframes);
  const applyingRef = useRef(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [duration, setDuration] = useState(0);

  keyframesRef.current = keyframes;

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const regions = RegionsPlugin.create();
    regionsRef.current = regions;
    const ws = WaveSurfer.create({
      container,
      url: audioUrl,
      waveColor: '#d4d4d8',
      progressColor: '#7c3aed',
      cursorColor: '#7c3aed',
      height: 96,
      plugins: [regions],
    });
    wavesurferRef.current = ws;

    ws.on('ready', () => {
      const d = ws.getDuration();
      setDuration(d);
      applyingRef.current = true;
      for (const regionData of buildRegions(keyframesRef.current)) {
        regions.addRegion(regionData);
      }
      applyingRef.current = false;
    });
    ws.on('timeupdate', (time) => {
      setCurrentTime(time);
      onPlayheadChange?.(time);
    });
    ws.on('play', () => setIsPlaying(true));
    ws.on('pause', () => setIsPlaying(false));

    regions.on('region-updated', (region: Region) => {
      if (applyingRef.current) return;
      const updated = keyframesRef.current.map((kf) =>
        kf.id === region.id ? { ...kf, startTime: region.start, endTime: region.end } : kf,
      );
      onKeyframesChange(updated);
    });

    // Click-to-add a keyframe on the waveform.
    if (canAdd) {
      const onClick = (event: MouseEvent) => {
        const rect = container.getBoundingClientRect();
        const ratio = (event.clientX - rect.left) / rect.width;
        const time = Math.max(0, ratio * ws.getDuration());
        const kf: Keyframe = {
          id: `kf-${Date.now()}`,
          projectId: '',
          sceneId: '',
          startTime: time,
          endTime: Math.min(time + 1, ws.getDuration() || time + 1),
          transitionDuration: 0.5,
          isAutoGenerated: false,
        };
        onKeyframesChange([...keyframesRef.current, kf]);
      };
      container.addEventListener('click', onClick);
      return () => {
        ws.destroy();
        container.removeEventListener('click', onClick);
      };
    }

    return () => {
      ws.destroy();
    };
  }, [audioUrl, canAdd, onKeyframesChange, onPlayheadChange]);

  // Re-sync regions when keyframes change externally (e.g. auto-sync).
  useEffect(() => {
    const regions = regionsRef.current;
    if (!regions || !duration || duration === 0) return;
    const existing = regions.getRegions().map((r) => r.id);
    const nextIds = keyframes.map((kf) => kf.id);
    if (existing.length === nextIds.length && existing.every((id) => nextIds.includes(id))) {
      return;
    }
    applyingRef.current = true;
    for (const region of regions.getRegions()) {
      region.remove();
    }
    for (const regionData of buildRegions(keyframes)) {
      regions.addRegion(regionData);
    }
    applyingRef.current = false;
  }, [keyframes, duration]);

  const togglePlay = () => {
    const ws = wavesurferRef.current;
    if (!ws) return;
    if (ws.isPlaying()) ws.pause();
    else void ws.play();
  };

  return (
    <div className="space-y-2">
      <div className="relative">
        <div ref={containerRef} className="w-full" />
        <KeyframeMarkers
          keyframes={keyframes}
          duration={duration}
          currentTime={currentTime}
          className="hidden"
        />
      </div>
      <div className="flex items-center justify-between">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={togglePlay}
          className="text-zinc-700"
        >
          {isPlaying ? <Pause className="mr-1.5 h-4 w-4" /> : <Play className="mr-1.5 h-4 w-4" />}
          {isPlaying ? 'Pause' : 'Play'}
        </Button>
        <div className="flex items-center gap-2 font-mono text-xs text-zinc-500">
          <span>{formatTime(currentTime)}</span>
          <span className="text-zinc-300">/</span>
          <span>{formatTime(duration)}</span>
        </div>
      </div>
    </div>
  );
}
