import { z } from "zod";

export const keyframeSchema = z
  .object({
    id: z.string().min(1),
    projectId: z.string().min(1),
    sceneId: z.string().min(1),
    startTime: z.number().nonnegative(),
    endTime: z.number().positive(),
    transitionDuration: z.number().nonnegative().default(0.5),
    isAutoGenerated: z.boolean().default(false),
  })
  .superRefine((keyframe, ctx) => {
    if (keyframe.endTime <= keyframe.startTime) {
      ctx.addIssue({
        code: "custom",
        path: ["endTime"],
        message: "endTime must be greater than startTime",
      });
    }
  });

export const audioTrackSchema = z.object({
  id: z.string().min(1),
  projectId: z.string().min(1),
  fileUrl: z.string().min(1),
  duration: z.number().nonnegative(),
  transcript: z.object({
    text: z.string(),
    language: z.string().default("unknown"),
    segments: z.array(
      z.object({
        id: z.number().int().nonnegative(),
        text: z.string(),
        start: z.number().nonnegative(),
        end: z.number().nonnegative(),
        words: z.array(
          z.object({
            word: z.string(),
            start: z.number().nonnegative(),
            end: z.number().nonnegative(),
          }),
        ),
      }),
    ),
  }),
});

export const autoSyncSuggestionSchema = z.object({
  sceneId: z.string().min(1),
  startTime: z.number().nonnegative(),
  endTime: z.number().positive(),
  confidence: z.number().min(0).max(1),
});

export type KeyframeInput = z.infer<typeof keyframeSchema>;
export type AudioTrackInput = z.infer<typeof audioTrackSchema>;
