import type { Scene, TextOverlay } from '@/types/scene';
import type { ThemeManifest } from '@/types/theme';
import { cameraMove, initialTransitionState, transitionIn } from './transition-library';

export interface SceneGenerationInput {
  scene: Scene;
  /** Asset path for the screenshot inside the generated project (e.g. `/assets/scene-0.png`). */
  assetPath: string;
  theme: ThemeManifest | null;
}

function overlayCode(overlay: TextOverlay, index: number, theme: ThemeManifest | null): string {
  const ref = `overlay${index}`;
  const fontFamily = overlay.fontFamily ?? theme?.fonts[0]?.family ?? 'sans-serif';
  // Motion Canvas view is 1920x1080; percentages → absolute coords.
  const x = (overlay.position.x / 100) * 1920;
  const y = (overlay.position.y / 100) * 1080;
  const fontSize = Math.round(overlay.fontSize * 3.6); // scale up for 1080p view
  return [
    `  const ${ref} = createRef<Txt>();`,
    `  view.add(`,
    `    <Txt ref={${ref}} text={${JSON.stringify(overlay.text)}} x={${x}} y={${y}} fontSize={${fontSize}} fill={'${overlay.color}'} fontFamily={'${fontFamily}'} opacity={0} textAlign={'center'} />,`,
    `  );`,
    `  yield* ${ref}().opacity(1, 0.8, easeInOutCubic);`,
  ].join('\n');
}

/**
 * Generates the Motion Canvas scene file for a single storyboard scene. Pure
 * string output — testable without a browser.
 */
export function generateSceneCode(input: SceneGenerationInput): string {
  const { scene, assetPath, theme } = input;
  const imgRef = 'img';
  const transitionSnippet = transitionIn(imgRef, scene.transition);
  const transitionState = initialTransitionState(imgRef, scene.transition);
  const camera = cameraMove(imgRef, scene.camera, scene.duration);

  const imports = new Set([
    "import { Img, Txt, makeScene2D } from '@motion-canvas/2d';",
    "import { createRef, easeInOutCubic } from '@motion-canvas/core';",
  ]);
  for (const extra of transitionSnippet.extraCoreImports) {
    imports.add(`import { createRef, easeInOutCubic, ${extra} } from '@motion-canvas/core';`);
  }

  const lines: string[] = [
    '// Generated by VDOMake — editable Motion Canvas scene.',
    ...imports,
    '',
    `export default makeScene2D(function* (view) {`,
    `  const ${imgRef} = createRef<Img>();`,
    `  view.add(`,
    `    <Img ref={${imgRef}} src={${JSON.stringify(assetPath)}} width={'100%'} height={'100%'} />,`,
    `  );`,
  ];

  // Initial transition state (off-screen position / zero opacity).
  for (const state of transitionState) {
    lines.push(`  ${state}`);
  }
  lines.push(`  ${transitionSnippet.inCode}`);

  // Text overlays.
  for (let index = 0; index < scene.overlays.length; index += 1) {
    lines.push(overlayCode(scene.overlays[index], index, theme));
  }

  // Camera movement over the scene duration.
  lines.push(`  ${camera.code}`);

  lines.push('});');
  lines.push('');
  return lines.join('\n');
}
